name: 52pojie_sign

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  5 11,23 * * * 
  watch:
    types: started
  
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 签到       
      run: |
        cookie='${{ secrets.COOKIE }}'
        SCKEY='${{ secrets.SCKEY }}'
        
       
       
        python 52pojie_sign.py <<EOF
        ${cookie}
        ${SCKEY}
        EOF
       
